#ifndef LOCATION_H
#define LOCATION_H
enum class LOCATION {
	MANAGER_SYSTEM,
	SYSTEM_ANIMATION,
	SYSTEM_COLLIDABLE,
	SYSTEM_CONTROLLABLE,
	SYSTEM_MOVEMENT,
	SYSTEM_RENDERER,
	SYSTEM_STATE,
	MESSAGE_HANDLER,
	MANAGER_EVENT,
	MANAGER_STATE,
	MANAGER_ENTITY,
	MANAGER_RESOURCE,
	MANAGER_TEXTURE,
	MANAGER_GUI,
	COMPONENT_BASE,
	COMPONENT_COLLISIONAABB,
	COMPONENT_SPRITE,
	COMPONENT_ANIMATION,
	COMPONENT_MOTION,
	COMPONENT_POSITION,
	COMPONENT_RETRIEVABLE,
	COMPONENT_STATE,
	GUI_INTERFACE,
	GUIELEMENT,
	FILEREADER,
	LOOKUP
};

#endif